name: Publish Release
on:
  release:
    types: [published, edited]
  workflow_dispatch:
jobs:
  publish-release:
    name: Publish release artifacts to package feeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Download all release assets
        uses: robinraju/release-downloader@v1.8
        with:
          releaseId: ${{ github.event.release.id }}
          fileName: '*'
          tarBall: false
          zipBall: false
          out-file-path: package-contents/runtimes
      - name: Setup package folder structure
        run: |
          cd package-contents/runtimes
          for d in */ ; do
            mkdir ${d}native ;
            mv ${d}libdeflate* ${d}native/ ;
          done
      - name: Pack
        run: dotnet pack -c Release -o pkg
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: LibDeflate.Native
          path: pkg/*
      - name: Publish the package to GPR
        run: dotnet nuget push pkg/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/jzebedee/index.json --skip-duplicate
      - name: Publish the package to NuGet
        run: dotnet nuget push pkg/*.nupkg -k ${{ secrets.LIBDEFLATE_NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate